name: Run Route Plan Script

on:
#  schedule:
#    # 注释不使用schedule，改用cron-job.org调用
#    # 每天 UTC 时间 23:20 运行（北京时间 07:20）
#    - cron: '20 23 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 输出当前时间
      - name: Print current time
        run: date
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 缓存 pip 依赖
      - name: Cache pip dependencies
        id: pip-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 运行脚本
      - name: Run route plan script
        env:
          BAIDU_MAP_AK: ${{ secrets.BAIDU_MAP_AK }}
          WECHAT_WEBHOOK_KEY: ${{ secrets.WECHAT_WEBHOOK_KEY }}
          ROUTE_ORIGIN: ${{ secrets.ROUTE_ORIGIN }}
          ROUTE_DESTINATION: ${{ secrets.ROUTE_DESTINATION }}
          ROUTE_WAYPOINTS: ${{ secrets.ROUTE_WAYPOINTS }}
        run: |
          python drive_planning.py