name: Run Route Plan Script

on:
  workflow_dispatch: # 允许手动触发
#  schedule:
#    # 注释不使用schedule，改用cron-job.org调用
#    # 每天 UTC 时间 23:20 运行（北京时间 07:20）
#    - cron: '20 23 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # 设置超时时间，避免任务卡住

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true  # 如果有新的运行，取消正在进行的任务

    steps:
      # 检出代码（设置 fetch-depth: 1 只获取最新的提交）
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.18'
          cache: 'pip'
          check-latest: false

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 运行脚本（使用 TZ 环境变量设置时区）
      - name: Run route plan script
        env:
          TZ: 'Asia/Shanghai'  # 设置时区为中国时区
          BAIDU_MAP_AK: ${{ secrets.BAIDU_MAP_AK }}
          WECHAT_WEBHOOK_KEY: ${{ secrets.WECHAT_WEBHOOK_KEY }}
          ROUTE_ORIGIN: ${{ secrets.ROUTE_ORIGIN }}
          ROUTE_DESTINATION: ${{ secrets.ROUTE_DESTINATION }}
          ROUTE_WAYPOINTS: ${{ secrets.ROUTE_WAYPOINTS }}
          RUN_MODE: '1'  # 节假日跳过模式
          DURATION_THRESHOLD: '40'  # 40分钟阈值
          PYTHONUNBUFFERED: 1  # 立即输出日志，不使用缓冲
        run: python drive_planning.py